In [1]:
import pandas as pd
import numpy as np
import os
import glob

In [2]:
precip_2018 = pd.read_csv("C:/Users/interactwel/Desktop/PRISM datasets/excel_to_text_script_folder/precipitation_data/precipitation_2018.csv")
precip_2018.head(7)

,date_prism,df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,...,df_41,df_42,df_43,df_44,df_45,df_46,df_47,df_48,df_49,df_50
0,1/1/2018,0.27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1/2/2018,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1/3/2018,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1/4/2018,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1/5/2018,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1/6/2018,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1/7/2018,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
precip_list = []
for filename in glob.glob('C:/Users/interactwel/Desktop/PRISM datasets/excel_to_text_script_folder/precipitation_data/*.csv'):
    precip_list.append(pd.read_csv(filename, index_col='date_prism',
    parse_dates=['date_prism']))
precip = pd.concat(precip_list, axis='columns') 
precip.head(100)

,df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,df_10,...,df_41,df_42,df_43,df_44,df_45,df_46,df_47,df_48,df_49,df_50
date_prism,,,,,,,,,,,,,,,,,,,,,
2018-01-01,0.27,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-04-06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-07,0.79,0.77,0.78,0.69,0.75,0.76,0.70,0.77,0.79,0.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-08,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-09,1.22,1.50,1.45,1.76,1.67,1.57,1.99,1.84,1.67,1.52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-10,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## PRECIPITATION DATA

In [4]:
import pandas as pd
import glob

# Create an empty list to store DataFrames
precip_list = []

# Read each CSV file and append to the list
for filename in glob.glob('C:/Users/interactwel/Desktop/PRISM datasets/excel_to_text_script_folder/precipitation_data/*.csv'):
    df = pd.read_csv(filename, index_col='date_prism', parse_dates=['date_prism'])
    precip_list.append(df)

# Concatenate the DataFrames along the columns axis
precip = pd.concat(precip_list, axis='columns')

# Display the first 100 rows
print(precip.head(100))

            df_1  df_2  df_3  df_4  df_5  df_6  df_7  df_8  df_9  df_10  ...  \
date_prism                                                               ...
2018-01-01  0.27  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  ...
2018-01-02  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  ...
2018-01-03  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  ...
2018-01-04  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  ...
2018-01-05  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  ...
...          ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...
2018-04-06  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  ...
2018-04-07  0.79  0.77  0.78  0.69  0.75  0.76  0.70  0.77  0.79   0.82  ...
2018-04-08  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  ...
2018-04-09  1.22  1.50  1.45  1.76  1.67  1.57  1.99  1.84  1.67   1.52  ...
2018-04-10  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   0.00  ...

            df_41  df_42  df_43  df_44  df_45  df_46  df_47  df_48  df_49  \
date_prism
2018-01-01    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2018-01-02    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2018-01-03    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2018-01-04    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2018-01-05    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
...           ...    ...    ...    ...    ...    ...    ...    ...    ...
2018-04-06    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2018-04-07    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2018-04-08    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2018-04-09    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2018-04-10    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            df_50
date_prism
2018-01-01    NaN
2018-01-02    NaN
2018-01-03    NaN
2018-01-04    NaN
2018-01-05    NaN
...           ...
2018-04-06    NaN
2018-04-07    NaN
2018-04-08    NaN
2018-04-09    NaN
2018-04-10    NaN

[100 rows x 250 columns]

In [6]:

# List of file names
file_names = [r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\precipitation_data\precipitation_2018.csv",
               r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\precipitation_data\precipitation_2019.csv", 
               r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\precipitation_data\precipitation_2020.csv",
                 r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\precipitation_data\precipitation_2021.csv", 
                 r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\precipitation_data\precipitation_2022.csv"
                 ]

# Read the first CSV file
df = pd.read_csv(file_names[0])

In [7]:
# Loop through the rest of the files and concatenate them
for file in file_names[1:]:
    temp_df = pd.read_csv(file)
    df = pd.concat([df, temp_df], ignore_index=True)

In [8]:
# Sort the DataFrame by date if necessary
df = df.sort_values(by='date_prism')

In [9]:
df.head(100)

,date_prism,df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,...,df_41,df_42,df_43,df_44,df_45,df_46,df_47,df_48,df_49,df_50
0,1/1/2018,0.27,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
365,1/1/2019,29.49,27.67,27.70,27.71,28.05,27.94,27.45,27.09,26.89,...,27.87,27.46,27.32,27.44,27.60,27.36,27.04,26.81,26.86,26.92
730,1/1/2020,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1096,1/1/2021,4.79,6.07,6.54,6.91,7.29,7.72,7.25,7.69,8.16,...,9.37,8.65,8.78,9.15,9.64,10.20,9.38,9.63,9.69,10.02
1461,1/1/2022,8.74,8.27,8.21,7.66,7.59,7.48,7.78,8.08,7.95,...,7.97,7.73,7.85,8.04,8.12,8.27,9.14,8.72,9.79,9.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,1/27/2018,2.64,4.32,6.03,3.96,5.39,7.20,3.64,4.57,6.16,...,1.91,0.86,0.93,1.74,1.86,1.85,0.66,0.67,0.47,0.40
391,1/27/2019,0.88,0.93,0.99,1.07,1.10,1.11,1.11,1.13,1.14,...,1.13,0.92,0.93,0.95,0.99,1.03,0.90,0.88,0.84,0.86
756,1/27/2020,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1122,1/27/2021,0.00,0.11,0.25,0.21,0.32,0.34,0.23,0.30,0.31,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1487,1/27/2022,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [10]:
# Save the merged DataFrame to a new CSV file
df.to_csv("Precipitation_data_big_watershed.csv", index=False)

## Temperature data

#### Maximum Temperature Data

In [14]:
# List of file names
file_names = [r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_max_2018.csv",
               r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_max_2019.csv", 
               r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_max_2020.csv",
                 r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_max_2021.csv", 
                 r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_max_2022.csv"
                 ]

# Read the first CSV file
df = pd.read_csv(file_names[0])

In [15]:
# Loop through the rest of the files and concatenate them
for file in file_names[1:]:
    temp_df = pd.read_csv(file)
    df = pd.concat([df, temp_df], ignore_index=True)


# Sort the DataFrame by date if necessary
df = df.sort_values(by='date_prism')

In [16]:
df.head(100)

,date_prism,tmax_1,tmax_2,tmax_3,tmax_4,tmax_5,tmax_6,tmax_7,tmax_8,tmax_9,...,tmax_41,tmax_42,tmax_43,tmax_44,tmax_45,tmax_46,tmax_47,tmax_48,tmax_49,tmax_50
0,1/1/2018,-10.2,-10.0,-10.0,-9.6,-9.8,-9.8,-9.5,-9.6,-9.6,...,-8.8,-8.1,-8.4,-8.6,-8.6,-8.6,-7.9,-8.3,-7.8,-8.1
365,1/1/2019,16.2,16.4,16.4,16.5,16.5,16.5,16.6,16.6,16.6,...,17.1,17.3,17.3,17.3,17.3,17.2,17.4,17.3,17.6,17.4
730,1/1/2020,2.5,2.5,2.5,2.5,2.6,2.6,2.6,2.6,2.6,...,2.6,2.6,2.9,2.9,2.7,2.7,2.8,2.8,3.0,2.9
1096,1/1/2021,0.0,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,0.3,0.6,0.5,0.6,0.6,0.4,0.6,0.6,0.7,0.7
1461,1/1/2022,16.4,16.8,16.7,17.0,17.0,17.0,17.1,17.1,17.1,...,17.6,17.9,17.8,17.8,17.8,17.7,17.9,17.8,18.0,17.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,1/27/2018,13.6,13.7,13.7,14.0,13.8,13.7,14.1,13.9,13.8,...,14.2,14.2,14.1,14.1,14.1,14.1,14.2,14.1,14.2,14.2
391,1/27/2019,1.1,1.3,1.4,1.6,1.6,1.6,1.8,1.8,1.8,...,2.1,2.3,2.4,2.4,2.3,2.3,2.4,2.4,2.6,2.4
756,1/27/2020,5.6,6.0,6.1,6.4,6.4,6.3,6.5,6.5,6.5,...,7.1,7.1,7.2,7.2,7.1,7.1,7.1,7.2,7.1,7.1
1122,1/27/2021,5.8,6.0,6.1,6.4,6.4,6.4,6.5,6.6,6.6,...,7.1,7.2,7.3,7.2,7.3,7.3,7.4,7.3,7.5,7.5
1487,1/27/2022,-5.6,-5.3,-5.3,-4.8,-4.8,-4.9,-4.5,-4.6,-4.6,...,-4.2,-4.2,-4.2,-4.2,-4.2,-4.2,-4.1,-4.2,-4.1,-4.1

In [17]:
# Save the merged DataFrame to a new CSV file
df.to_csv("Max_Temperature_data_big_watershed.csv", index=False)

### Minimum Temperature Data

In [18]:
# List of file names
file_names = [r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_min_2018.csv",
               r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_min_2019.csv", 
               r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_min_2020.csv",
                 r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_min_2021.csv", 
                 r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\temp_min_2022.csv"
                 ]

# Read the first CSV file
df = pd.read_csv(file_names[0])

In [19]:
# Loop through the rest of the files and concatenate them
for file in file_names[1:]:
    temp_df = pd.read_csv(file)
    df = pd.concat([df, temp_df], ignore_index=True)


# Sort the DataFrame by date if necessary
df = df.sort_values(by='date_prism')

In [20]:
df.head(100)

,date_prism,tm_1,tm_2,tm_3,tm_4,tm_5,tm_6,tm_7,tm_8,tm_9,...,tm_41,tm_42,tm_43,tm_44,tm_45,tm_46,tm_47,tm_48,tm_49,tm_50
0,1/1/2018,-19.7,-19.7,-19.8,-19.3,-19.5,-19.7,-19.2,-19.3,-19.5,...,-18.7,-18.5,-18.5,-18.6,-18.6,-18.7,-18.5,-18.6,-18.3,-18.5
365,1/1/2019,3.8,3.8,3.8,4.2,4.1,3.9,4.3,4.3,4.2,...,4.7,4.6,4.5,4.7,4.8,4.8,4.7,4.5,4.7,4.6
730,1/1/2020,0.2,0.0,0.0,-0.1,-0.1,0.0,0.0,0.0,0.1,...,-0.1,-0.2,0.0,0.0,-0.1,-0.1,-0.1,-0.1,-0.1,0.0
1096,1/1/2021,-3.6,-3.4,-3.6,-3.1,-3.2,-3.5,-3.0,-3.1,-3.2,...,-2.4,-2.6,-2.4,-2.4,-2.4,-2.3,-2.5,-2.4,-2.2,-2.2
1461,1/1/2022,7.8,7.9,7.8,8.3,8.2,8.1,8.4,8.4,8.2,...,8.6,8.9,8.7,8.8,8.6,8.6,8.8,8.7,8.7,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,1/27/2018,-0.7,-0.6,-0.6,-0.2,-0.5,-0.4,-0.2,-0.3,-0.6,...,0.5,1.3,1.2,1.2,1.1,0.9,1.6,1.2,1.9,1.6
391,1/27/2019,-5.2,-5.1,-5.2,-4.6,-4.8,-4.8,-4.4,-4.3,-4.4,...,-3.7,-3.6,-3.6,-3.5,-3.6,-3.6,-3.5,-3.6,-3.5,-3.5
756,1/27/2020,-3.2,-3.2,-3.2,-3.3,-3.3,-3.2,-3.3,-3.2,-3.2,...,-3.0,-2.7,-2.8,-2.8,-2.7,-2.9,-2.6,-2.8,-2.5,-2.5
1122,1/27/2021,-1.2,-1.3,-1.3,-1.1,-1.1,-1.2,-1.0,-1.0,-1.0,...,-0.7,-0.6,-0.5,-0.5,-0.6,-0.7,-0.3,-0.3,-0.2,-0.3
1487,1/27/2022,-16.6,-16.4,-16.5,-16.1,-16.2,-16.3,-16.0,-16.1,-16.2,...,-15.2,-14.5,-14.7,-14.8,-14.9,-15.0,-14.4,-14.5,-14.3,-14.3

In [21]:
# Save the merged DataFrame to a new CSV file
df.to_csv("Min_Temperature_data_big_watershed.csv", index=False)