In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
prism_2019 = pd.read_csv(r"C:\Users\interactwel\Desktop\PRISM datasets\excel_to_text_script_folder\Big_watershed_PRISM\PRISM_ppt_tmin_tmax_stable_4km_20190101_20191231.csv", header=10)

In [3]:
prism_2019.head(10)

,Name,Longitude,Latitude,Elevation (m),Date,ppt (mm),tmin (degrees C),tmax (degrees C)
0,Location 1,-85.3742,39.3169,313,2019-01-01,29.49,3.8,16.2
1,Location 1,-85.3742,39.3169,313,2019-01-02,0.00,2.5,5.1
2,Location 1,-85.3742,39.3169,313,2019-01-03,0.00,-0.6,4.2
3,Location 1,-85.3742,39.3169,313,2019-01-04,0.00,-2.0,3.6
4,Location 1,-85.3742,39.3169,313,2019-01-05,21.05,-1.5,10.3
5,Location 1,-85.3742,39.3169,313,2019-01-06,0.00,-0.9,11.0
6,Location 1,-85.3742,39.3169,313,2019-01-07,0.00,-0.9,10.2
7,Location 1,-85.3742,39.3169,313,2019-01-08,0.00,6.0,13.3
8,Location 1,-85.3742,39.3169,313,2019-01-09,0.00,-2.7,15.6
9,Location 1,-85.3742,39.3169,313,2019-01-10,0.00,-6.6,-2.7

## Precipitation extraction

In [4]:
prism_2019.columns

Index(['Name', 'Longitude', 'Latitude', 'Elevation (m)', 'Date', 'ppt (mm)',
       'tmin (degrees C)', 'tmax (degrees C)'],
      dtype='object')

In [6]:
prism_2019.reset_index(drop=True, inplace=True)

In [18]:
df_1 = prism_2019['ppt (mm)'][prism_2018['Name'] == 'Location 1']
df_2 = prism_2018['ppt (mm)'][prism_2018['Name'] == 'Location 2']
date_prism = prism_2018['Date'][prism_2018['Name'] == 'Location 1']

In [22]:
df_1.reset_index(drop=True, inplace=True)
df_2.reset_index(drop=True, inplace=True)
date_prism.reset_index(drop=True, inplace=True)

In [23]:
df = pd.DataFrame({'date_prism': date_prism, 'df_1': df_1, 'df_2': df_2})

In [24]:
df.head(10)

   date_prism   df_1  df_2
0  2018-01-01   0.27  0.00
1  2018-01-02   0.00  0.00
2  2018-01-03   0.00  0.00
3  2018-01-04   0.00  0.00
4  2018-01-05   0.00  0.00
5  2018-01-06   0.00  0.00
6  2018-01-07   0.00  0.00
7  2018-01-08  11.66  9.77
8  2018-01-09   0.00  0.27
9  2018-01-10   0.39  0.38

In [5]:
# creating new columns of precipitation data for each location
date_prism = prism_2019['Date'][prism_2019['Name'] == 'Location 1']
df_1 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 1']
df_2 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 2']
df_3 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 3']
df_4 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 4']
df_5 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 5']
df_6 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 6']
df_7 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 7']
df_8 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 8']
df_9 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 9']
df_10 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 10']
df_11 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 11']
df_12 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 12']
df_13 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 13']
df_14 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 14']
df_15 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 15']
df_16 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 16']
df_17 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 17']
df_18 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 18']
df_19 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 19']
df_20 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 20']
df_21 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 21']
df_22 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 22']
df_23 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 23']
df_24 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 24']
df_25 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 25']
df_26 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 26']
df_27 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 27']
df_28 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 28']
df_29 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 29']
df_30 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 30']
df_31 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 31']
df_32 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 32']
df_33 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 33']
df_34 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 34']
df_35 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 35']
df_36 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 36']
df_37 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 37']
df_38 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 38']
df_39 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 39']
df_40 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 40']
df_41 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 41']
df_42 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 42']
df_43 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 43']
df_44 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 44']
df_45 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 45']
df_46 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 46']
df_47 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 47']
df_48 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 48']
df_49 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 49']
df_50 = prism_2019['ppt (mm)'][prism_2019['Name'] == 'Location 50']

In [25]:
df_1.shape

(365,)

In [6]:
date_prism.reset_index(drop=True, inplace=True)
df_1.reset_index(drop=True, inplace=True)
df_2.reset_index(drop=True, inplace=True)
df_3.reset_index(drop=True, inplace=True)
df_4.reset_index(drop=True, inplace=True)
df_5.reset_index(drop=True, inplace=True)
df_6.reset_index(drop=True, inplace=True)
df_7.reset_index(drop=True, inplace=True)
df_8.reset_index(drop=True, inplace=True)
df_9.reset_index(drop=True, inplace=True)
df_10.reset_index(drop=True, inplace=True)
df_11.reset_index(drop=True, inplace=True)
df_12.reset_index(drop=True, inplace=True)
df_13.reset_index(drop=True, inplace=True)
df_14.reset_index(drop=True, inplace=True)
df_15.reset_index(drop=True, inplace=True)
df_16.reset_index(drop=True, inplace=True)
df_17.reset_index(drop=True, inplace=True)
df_18.reset_index(drop=True, inplace=True)
df_19.reset_index(drop=True, inplace=True)
df_20.reset_index(drop=True, inplace=True)
df_21.reset_index(drop=True, inplace=True)
df_22.reset_index(drop=True, inplace=True)
df_23.reset_index(drop=True, inplace=True)
df_24.reset_index(drop=True, inplace=True)
df_25.reset_index(drop=True, inplace=True)
df_26.reset_index(drop=True, inplace=True)
df_27.reset_index(drop=True, inplace=True)
df_28.reset_index(drop=True, inplace=True)
df_29.reset_index(drop=True, inplace=True)
df_30.reset_index(drop=True, inplace=True)
df_31.reset_index(drop=True, inplace=True)
df_32.reset_index(drop=True, inplace=True)
df_33.reset_index(drop=True, inplace=True)
df_34.reset_index(drop=True, inplace=True)
df_35.reset_index(drop=True, inplace=True)
df_36.reset_index(drop=True, inplace=True)
df_37.reset_index(drop=True, inplace=True)
df_38.reset_index(drop=True, inplace=True)
df_39.reset_index(drop=True, inplace=True)
df_40.reset_index(drop=True, inplace=True)
df_41.reset_index(drop=True, inplace=True)
df_42.reset_index(drop=True, inplace=True)
df_43.reset_index(drop=True, inplace=True)
df_44.reset_index(drop=True, inplace=True)
df_45.reset_index(drop=True, inplace=True)
df_46.reset_index(drop=True, inplace=True)
df_47.reset_index(drop=True, inplace=True)
df_48.reset_index(drop=True, inplace=True)
df_49.reset_index(drop=True, inplace=True)
df_50.reset_index(drop=True, inplace=True)

In [16]:
df_11

3650     0.00
3651     0.00
3652     0.00
3653     0.00
3654     0.00
        ...
4010     0.00
4011    10.15
4012     0.00
4013     0.00
4014    11.59
Name: ppt (mm), Length: 365, dtype: float64

In [17]:
df_12

4015     0.00
4016     0.00
4017     0.00
4018     0.00
4019     0.00
        ...
4375     0.00
4376    10.33
4377     0.00
4378     0.00
4379    12.20
Name: ppt (mm), Length: 365, dtype: float64

In [7]:
Precipitation_Prism_data = pd.DataFrame({'date_prism': date_prism, 'df_1': df_1, 'df_2': df_2, 'df_3': df_3, 'df_4': df_4, 'df_5': df_5, 'df_6': df_6, 'df_7': df_7, 'df_8': df_8, 'df_9': df_9, 'df_10': df_10, 'df_11': df_11, 'df_12': df_12, 'df_13': df_13, 'df_14': df_14, 'df_15': df_15, 'df_16': df_16, 'df_17': df_17, 'df_18': df_18, 'df_19': df_19, 'df_20': df_20, 'df_21': df_21, 'df_22': df_22, 'df_23': df_23, 'df_24': df_24, 'df_25': df_25, 'df_26': df_26, 'df_27': df_27, 'df_28': df_28, 'df_29': df_29, 'df_30': df_30, 'df_31': df_31, 'df_32': df_32, 'df_33': df_33, 'df_34': df_34, 'df_35': df_35, 'df_36': df_36, 'df_37': df_37, 'df_38': df_38, 'df_39': df_39, 'df_40': df_40, 'df_41': df_41, 'df_42': df_42, 'df_43': df_43, 'df_44': df_44, 'df_45': df_45, 'df_46': df_46, 'df_47': df_47, 'df_48': df_48, 'df_49': df_49, 'df_50': df_50})

In [8]:
Precipitation_Prism_data.head(15)

,date_prism,df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,...,df_41,df_42,df_43,df_44,df_45,df_46,df_47,df_48,df_49,df_50
0,2019-01-01,29.49,27.67,27.70,27.71,28.05,27.94,27.45,27.09,26.89,...,27.87,27.46,27.32,27.44,27.60,27.36,27.04,26.81,26.86,26.92
1,2019-01-02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,2019-01-03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,2019-01-04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,2019-01-05,21.05,21.36,21.80,17.55,16.99,16.64,15.65,15.11,14.70,...,13.45,14.18,13.86,13.49,13.39,13.37,14.02,13.69,13.68,13.58
5,2019-01-06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,2019-01-07,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7,2019-01-08,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.36,0.49,0.48,0.46,0.48,0.51,0.53,0.53,0.55,0.55
8,2019-01-09,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
9,2019-01-10,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,2019-01-11,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
11,2019-01-12,5.06,5.73,5.63,7.78,7.81,7.24,8.03,7.97,7.94,...,7.34,7.87,7.80,7.87,8.07,8.23,8.37,8.49,9.17,9.26
12,2019-01-13,18.46,18.32,19.60,18.10,18.82,20.31,17.36,17.17,18.08,...,11.57,10.57,10.40,10.39,10.37,10.53,10.42,10.31,10.61,10.54
13,2019-01-14,0.82,0.68,0.83,0.08,0.31,0.47,0.00,0.00,0.22,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
14,2019-01-15,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [9]:
Precipitation_Prism_data.to_csv('precipitation_2019.csv')

## Temperature minimum Extraction

In [10]:
# creating new columns of temp min  data for each location
# date_prism = prism_2018['Date'][prism_2018['Name'] == 'Location 1']
tm_1 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 1']
tm_2 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 2']
tm_3 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 3']
tm_4 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 4']
tm_5 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 5']
tm_6 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 6']
tm_7 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 7']
tm_8 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 8']
tm_9 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 9']
tm_10 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 10']
tm_11 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 11']
tm_12 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 12']
tm_13 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 13']
tm_14 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 14']
tm_15 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 15']
tm_16 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 16']
tm_17 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 17']
tm_18 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 18']
tm_19 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 19']
tm_20 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 20']
tm_21 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 21']
tm_22 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 22']
tm_23 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 23']
tm_24 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 24']
tm_25 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 25']
tm_26 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 26']
tm_27 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 27']
tm_28 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 28']
tm_29 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 29']
tm_30 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 30']
tm_31 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 31']
tm_32 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 32']
tm_33 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 33']
tm_34 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 34']
tm_35 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 35']
tm_36 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 36']
tm_37 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 37']
tm_38 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 38']
tm_39 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 39']
tm_40 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 40']
tm_41 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 41']
tm_42 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 42']
tm_43 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 43']
tm_44 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 44']
tm_45 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 45']
tm_46 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 46']
tm_47 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 47']
tm_48 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 48']
tm_49 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 49']
tm_50 = prism_2019['tmin (degrees C)'][prism_2019['Name'] == 'Location 50']

In [11]:
# date_prism.reset_index(drop=True, inplace=True)
tm_1.reset_index(drop=True, inplace=True)
tm_2.reset_index(drop=True, inplace=True)
tm_3.reset_index(drop=True, inplace=True)
tm_4.reset_index(drop=True, inplace=True)
tm_5.reset_index(drop=True, inplace=True)
tm_6.reset_index(drop=True, inplace=True)
tm_7.reset_index(drop=True, inplace=True)
tm_8.reset_index(drop=True, inplace=True)
tm_9.reset_index(drop=True, inplace=True)
tm_10.reset_index(drop=True, inplace=True)
tm_11.reset_index(drop=True, inplace=True)
tm_12.reset_index(drop=True, inplace=True)
tm_13.reset_index(drop=True, inplace=True)
tm_14.reset_index(drop=True, inplace=True)
tm_15.reset_index(drop=True, inplace=True)
tm_16.reset_index(drop=True, inplace=True)
tm_17.reset_index(drop=True, inplace=True)
tm_18.reset_index(drop=True, inplace=True)
tm_19.reset_index(drop=True, inplace=True)
tm_20.reset_index(drop=True, inplace=True)
tm_21.reset_index(drop=True, inplace=True)
tm_22.reset_index(drop=True, inplace=True)
tm_23.reset_index(drop=True, inplace=True)
tm_24.reset_index(drop=True, inplace=True)
tm_25.reset_index(drop=True, inplace=True)
tm_26.reset_index(drop=True, inplace=True)
tm_27.reset_index(drop=True, inplace=True)
tm_28.reset_index(drop=True, inplace=True)
tm_29.reset_index(drop=True, inplace=True)
tm_30.reset_index(drop=True, inplace=True)
tm_31.reset_index(drop=True, inplace=True)
tm_32.reset_index(drop=True, inplace=True)
tm_33.reset_index(drop=True, inplace=True)
tm_34.reset_index(drop=True, inplace=True)
tm_35.reset_index(drop=True, inplace=True)
tm_36.reset_index(drop=True, inplace=True)
tm_37.reset_index(drop=True, inplace=True)
tm_38.reset_index(drop=True, inplace=True)
tm_39.reset_index(drop=True, inplace=True)
tm_40.reset_index(drop=True, inplace=True)
tm_41.reset_index(drop=True, inplace=True)
tm_42.reset_index(drop=True, inplace=True)
tm_43.reset_index(drop=True, inplace=True)
tm_44.reset_index(drop=True, inplace=True)
tm_45.reset_index(drop=True, inplace=True)
tm_46.reset_index(drop=True, inplace=True)
tm_47.reset_index(drop=True, inplace=True)
tm_48.reset_index(drop=True, inplace=True)
tm_49.reset_index(drop=True, inplace=True)
tm_50.reset_index(drop=True, inplace=True)

In [12]:
temperature_min_prism_data =  pd.DataFrame({'date_prism': date_prism, 'tm_1': tm_1, 'tm_2': tm_2, 'tm_3': tm_3, 'tm_4': tm_4, 'tm_5': tm_5, 'tm_6': tm_6, 'tm_7': tm_7, 'tm_8': tm_8, 'tm_9': tm_9, 'tm_10': tm_10, 'tm_11': tm_11, 'tm_12': tm_12, 'tm_13': tm_13, 'tm_14': tm_14, 'tm_15': tm_15, 'tm_16': tm_16, 'tm_17': tm_17, 'tm_18': tm_18, 'tm_19': tm_19, 'tm_20': tm_20, 'tm_21': tm_21, 'tm_22': tm_22, 'tm_23': tm_23, 'tm_24': tm_24, 'tm_25': tm_25, 'tm_26': tm_26, 'tm_27': tm_27, 'tm_28': tm_28, 'tm_29': tm_29, 'tm_30': tm_30, 'tm_31': tm_31, 'tm_32': tm_32, 'tm_33': tm_33, 'tm_34': tm_34, 'tm_35': tm_35, 'tm_36': tm_36, 'tm_37': tm_37, 'tm_38': tm_38, 'tm_39': tm_39, 'tm_40': tm_40, 'tm_41': tm_41, 'tm_42': tm_42, 'tm_43': tm_43, 'tm_44': tm_44, 'tm_45': tm_45, 'tm_46': tm_46, 'tm_47': tm_47, 'tm_48': tm_48, 'tm_49': tm_49, 'tm_50': tm_50})

In [13]:
temperature_min_prism_data.head(15)

,date_prism,tm_1,tm_2,tm_3,tm_4,tm_5,tm_6,tm_7,tm_8,tm_9,...,tm_41,tm_42,tm_43,tm_44,tm_45,tm_46,tm_47,tm_48,tm_49,tm_50
0,2019-01-01,3.8,3.8,3.8,4.2,4.1,3.9,4.3,4.3,4.2,...,4.7,4.6,4.5,4.7,4.8,4.8,4.7,4.5,4.7,4.6
1,2019-01-02,2.5,2.6,2.5,2.8,2.7,2.6,2.8,2.8,2.7,...,3.1,3.1,3.2,3.2,3.2,3.1,3.1,3.1,3.2,3.2
2,2019-01-03,-0.6,-0.5,-0.6,-0.1,-0.2,-0.5,0.0,-0.0,-0.2,...,0.3,0.1,0.2,0.3,0.3,0.3,0.2,0.2,0.3,0.3
3,2019-01-04,-2.0,-2.0,-2.0,-1.9,-1.9,-2.0,-1.8,-1.9,-1.9,...,-1.1,-1.0,-0.9,-1.0,-0.9,-1.0,-0.9,-0.9,-0.8,-0.8
4,2019-01-05,-1.5,-1.2,-1.3,-0.9,-0.9,-1.1,-0.7,-0.7,-0.8,...,-0.0,-0.1,-0.1,-0.0,0.0,-0.0,-0.0,-0.1,0.1,0.1
5,2019-01-06,-0.9,-0.8,-0.8,-0.8,-0.8,-0.8,-0.8,-0.8,-0.8,...,-0.2,-0.1,-0.1,-0.1,-0.1,-0.2,-0.0,-0.1,0.1,0.0
6,2019-01-07,-0.9,-0.8,-0.9,-0.8,-0.8,-0.8,-0.7,-0.8,-0.8,...,-0.1,0.2,0.1,0.1,0.1,-0.0,0.3,0.1,0.4,0.3
7,2019-01-08,6.0,6.3,6.2,6.6,6.4,6.3,6.6,6.5,6.3,...,7.6,8.3,8.0,7.8,8.0,7.9,8.3,8.0,8.3,8.2
8,2019-01-09,-2.7,-2.7,-2.8,-2.4,-2.5,-2.7,-2.3,-2.3,-2.4,...,-1.4,-1.2,-1.3,-1.4,-1.4,-1.4,-1.1,-1.4,-1.2,-1.3
9,2019-01-10,-6.6,-6.5,-6.6,-6.5,-6.5,-6.6,-6.4,-6.5,-6.5,...,-6.5,-6.8,-6.5,-6.4,-6.6,-6.6,-6.8,-6.6,-6.7,-6.7
10,2019-01-11,-6.8,-6.8,-6.9,-6.8,-6.9,-7.0,-6.8,-6.9,-6.9,...,-7.1,-7.5,-7.2,-7.2,-7.2,-7.3,-7.4,-7.2,-7.2,-7.1
11,2019-01-12,-5.1,-5.5,-5.4,-6.2,-6.1,-5.8,-6.3,-6.3,-6.1,...,-6.9,-7.2,-7.2,-7.1,-7.0,-6.9,-7.2,-7.1,-7.1,-7.1
12,2019-01-13,-2.6,-2.5,-2.6,-2.4,-2.4,-2.5,-2.3,-2.3,-2.4,...,-1.7,-1.4,-1.5,-1.5,-1.5,-1.6,-1.3,-1.5,-1.2,-1.4
13,2019-01-14,-4.1,-4.2,-4.2,-3.8,-3.9,-4.1,-3.7,-3.7,-3.8,...,-3.3,-3.5,-3.4,-3.4,-3.5,-3.4,-3.3,-3.4,-3.3,-3.3
14,2019-01-15,-11.9,-11.3,-11.6,-10.5,-10.8,-11.2,-10.1,-10.2,-10.5,...,-7.5,-6.8,-6.9,-7.0,-7.0,-7.1,-6.4,-6.8,-6.0,-6.2

In [14]:
temperature_min_prism_data.to_csv('temp_min_2019.csv')

## Temperature Maximum Extraction.

In [15]:
# creating new columns of temp min  data for each location
# date_prism = prism_2018['Date'][prism_2018['Name'] == 'Location 1']
tmax_1 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 1']
tmax_2 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 2']
tmax_3 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 3']
tmax_4 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 4']
tmax_5 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 5']
tmax_6 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 6']
tmax_7 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 7']
tmax_8 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 8']
tmax_9 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 9']
tmax_10 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 10']
tmax_11 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 11']
tmax_12 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 12']
tmax_13 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 13']
tmax_14 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 14']
tmax_15 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 15']
tmax_16 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 16']
tmax_17 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 17']
tmax_18 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 18']
tmax_19 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 19']
tmax_20 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 20']
tmax_21 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 21']
tmax_22 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 22']
tmax_23 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 23']
tmax_24 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 24']
tmax_25 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 25']
tmax_26 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 26']
tmax_27 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 27']
tmax_28 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 28']
tmax_29 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 29']
tmax_30 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 30']
tmax_31 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 31']
tmax_32 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 32']
tmax_33 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 33']
tmax_34 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 34']
tmax_35 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 35']
tmax_36 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 36']
tmax_37 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 37']
tmax_38 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 38']
tmax_39 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 39']
tmax_40 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 40']
tmax_41 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 41']
tmax_42 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 42']
tmax_43 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 43']
tmax_44 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 44']
tmax_45 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 45']
tmax_46 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 46']
tmax_47 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 47']
tmax_48 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 48']
tmax_49 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 49']
tmax_50 = prism_2019['tmax (degrees C)'][prism_2019['Name'] == 'Location 50']

In [16]:
# date_prism.reset_index(drop=True, inplace=True)
tmax_1.reset_index(drop=True, inplace=True)
tmax_2.reset_index(drop=True, inplace=True)
tmax_3.reset_index(drop=True, inplace=True)
tmax_4.reset_index(drop=True, inplace=True)
tmax_5.reset_index(drop=True, inplace=True)
tmax_6.reset_index(drop=True, inplace=True)
tmax_7.reset_index(drop=True, inplace=True)
tmax_8.reset_index(drop=True, inplace=True)
tmax_9.reset_index(drop=True, inplace=True)
tmax_10.reset_index(drop=True, inplace=True)
tmax_11.reset_index(drop=True, inplace=True)
tmax_12.reset_index(drop=True, inplace=True)
tmax_13.reset_index(drop=True, inplace=True)
tmax_14.reset_index(drop=True, inplace=True)
tmax_15.reset_index(drop=True, inplace=True)
tmax_16.reset_index(drop=True, inplace=True)
tmax_17.reset_index(drop=True, inplace=True)
tmax_18.reset_index(drop=True, inplace=True)
tmax_19.reset_index(drop=True, inplace=True)
tmax_20.reset_index(drop=True, inplace=True)
tmax_21.reset_index(drop=True, inplace=True)
tmax_22.reset_index(drop=True, inplace=True)
tmax_23.reset_index(drop=True, inplace=True)
tmax_24.reset_index(drop=True, inplace=True)
tmax_25.reset_index(drop=True, inplace=True)
tmax_26.reset_index(drop=True, inplace=True)
tmax_27.reset_index(drop=True, inplace=True)
tmax_28.reset_index(drop=True, inplace=True)
tmax_29.reset_index(drop=True, inplace=True)
tmax_30.reset_index(drop=True, inplace=True)
tmax_31.reset_index(drop=True, inplace=True)
tmax_32.reset_index(drop=True, inplace=True)
tmax_33.reset_index(drop=True, inplace=True)
tmax_34.reset_index(drop=True, inplace=True)
tmax_35.reset_index(drop=True, inplace=True)
tmax_36.reset_index(drop=True, inplace=True)
tmax_37.reset_index(drop=True, inplace=True)
tmax_38.reset_index(drop=True, inplace=True)
tmax_39.reset_index(drop=True, inplace=True)
tmax_40.reset_index(drop=True, inplace=True)
tmax_41.reset_index(drop=True, inplace=True)
tmax_42.reset_index(drop=True, inplace=True)
tmax_43.reset_index(drop=True, inplace=True)
tmax_44.reset_index(drop=True, inplace=True)
tmax_45.reset_index(drop=True, inplace=True)
tmax_46.reset_index(drop=True, inplace=True)
tmax_47.reset_index(drop=True, inplace=True)
tmax_48.reset_index(drop=True, inplace=True)
tmax_49.reset_index(drop=True, inplace=True)
tmax_50.reset_index(drop=True, inplace=True)

In [17]:
temperature_max_prism_data =  pd.DataFrame({'date_prism': date_prism, 'tmax_1': tmax_1, 'tmax_2': tmax_2, 'tmax_3': tmax_3, 'tmax_4': tmax_4, 'tmax_5': tmax_5, 'tmax_6': tmax_6, 'tmax_7': tmax_7, 'tmax_8': tmax_8, 'tmax_9': tmax_9, 'tmax_10': tmax_10, 'tmax_11': tmax_11, 'tmax_12': tmax_12, 'tmax_13': tmax_13, 'tmax_14': tmax_14, 'tmax_15': tmax_15, 'tmax_16': tmax_16, 'tmax_17': tmax_17, 'tmax_18': tmax_18, 'tmax_19': tmax_19, 'tmax_20': tmax_20, 'tmax_21': tmax_21, 'tmax_22': tmax_22, 'tmax_23': tmax_23, 'tmax_24': tmax_24, 'tmax_25': tmax_25, 'tmax_26': tmax_26, 'tmax_27': tmax_27, 'tmax_28': tmax_28, 'tmax_29': tmax_29, 'tmax_30': tmax_30, 'tmax_31': tmax_31, 'tmax_32': tmax_32, 'tmax_33': tmax_33, 'tmax_34': tmax_34, 'tmax_35': tmax_35, 'tmax_36': tmax_36, 'tmax_37': tmax_37, 'tmax_38': tmax_38, 'tmax_39': tmax_39, 'tmax_40': tmax_40, 'tmax_41': tmax_41, 'tmax_42': tmax_42, 'tmax_43': tmax_43, 'tmax_44': tmax_44, 'tmax_45': tmax_45, 'tmax_46': tmax_46, 'tmax_47': tmax_47, 'tmax_48': tmax_48, 'tmax_49': tmax_49, 'tmax_50': tmax_50})

In [18]:
temperature_max_prism_data.head(15)

,date_prism,tmax_1,tmax_2,tmax_3,tmax_4,tmax_5,tmax_6,tmax_7,tmax_8,tmax_9,...,tmax_41,tmax_42,tmax_43,tmax_44,tmax_45,tmax_46,tmax_47,tmax_48,tmax_49,tmax_50
0,2019-01-01,16.2,16.4,16.4,16.5,16.5,16.5,16.6,16.6,16.6,...,17.1,17.3,17.3,17.3,17.3,17.2,17.4,17.3,17.6,17.4
1,2019-01-02,5.1,5.2,5.2,5.4,5.4,5.3,5.4,5.4,5.4,...,5.6,5.8,5.8,5.8,5.8,5.7,5.8,5.8,6.0,5.9
2,2019-01-03,4.2,4.3,4.4,4.5,4.5,4.6,4.7,4.7,4.7,...,4.9,4.8,4.9,4.9,4.9,4.9,4.8,4.9,4.9,4.8
3,2019-01-04,3.6,3.8,3.8,4.1,4.0,3.9,4.1,4.1,4.1,...,4.9,5.2,5.1,5.0,5.2,5.1,5.2,5.0,5.2,5.2
4,2019-01-05,10.3,10.4,10.3,10.4,10.4,10.3,10.4,10.3,10.3,...,10.2,10.2,10.2,10.1,10.3,10.3,10.0,10.0,9.9,9.9
5,2019-01-06,11.0,11.3,11.2,11.6,11.5,11.6,11.7,11.7,11.8,...,12.2,12.5,12.5,12.4,12.4,12.3,12.5,12.4,12.6,12.5
6,2019-01-07,10.2,10.5,10.5,11.0,11.0,10.9,11.2,11.2,11.1,...,12.2,12.9,12.8,12.7,12.6,12.5,13.0,12.8,13.2,13.0
7,2019-01-08,13.3,13.5,13.5,13.8,13.8,13.7,13.9,13.9,14.0,...,14.4,14.6,14.6,14.6,14.6,14.6,14.6,14.5,14.8,14.6
8,2019-01-09,15.6,15.7,15.8,15.9,15.9,15.9,16.0,16.0,16.0,...,16.1,16.1,16.2,16.3,16.1,16.1,16.1,16.2,16.2,16.1
9,2019-01-10,-2.7,-2.4,-2.4,-1.9,-1.9,-2.0,-1.8,-1.8,-1.8,...,-0.6,-0.3,-0.2,-0.2,-0.3,-0.3,-0.1,-0.2,0.1,-0.1
10,2019-01-11,-2.7,-2.6,-2.6,-2.3,-2.3,-2.4,-2.2,-2.2,-2.2,...,-1.3,-0.5,-0.6,-0.7,-0.7,-0.8,-0.4,-0.6,-0.1,-0.4
11,2019-01-12,0.2,0.4,0.4,0.6,0.6,0.5,0.7,0.6,0.6,...,0.9,1.2,1.2,1.1,1.1,1.0,1.2,1.1,1.3,1.1
12,2019-01-13,0.0,0.2,0.2,0.5,0.5,0.4,0.6,0.6,0.6,...,1.4,1.9,1.9,1.8,1.7,1.6,2.0,1.9,2.2,2.0
13,2019-01-14,-0.1,-0.1,-0.0,0.0,0.0,0.0,0.1,0.0,0.1,...,0.6,1.1,1.0,0.9,0.9,0.8,1.1,1.0,1.3,1.1
14,2019-01-15,-1.2,-0.9,-1.0,-0.7,-0.8,-0.9,-0.6,-0.7,-0.8,...,0.4,1.3,1.0,0.9,0.8,0.6,1.3,1.0,1.5,1.2

In [19]:
temperature_max_prism_data.to_csv('temp_max_2019.csv')